# -*- coding: utf-8 -*-
"""dota.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k2VrZqMmFV7LMXRQfVTRFsf4dsgTSV7N

# BIBLIOTECAS PARA FUNCIONAMENTO
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup
import numpy as np

"""PREPARANDO O AMBINETE PARA O WEB SCRAPING DO SITE DOTABUFF"""

url = 'https://pt.dotabuff.com/heroes'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'}
site = requests.get(url, headers=headers)
soup = BeautifulSoup(site.text, 'html.parser')

hero_name = list()
for hero in soup.find_all('div', attrs={'class':'hero'}):
  heroi = hero.find('div', attrs={'class':'name'}).text
  hero_name.append(heroi)


dota = pd.DataFrame(hero_name, columns=['Herois'])
dota.index = np.arange(1, len(dota) + 1)
display(dota)

def buscar_heroi(nome_heroi): # realiza o nome do heroi, retorna os 10 herois que sao
                              # fortes ou fracos contra o nome fornecido como argumento
  nome = nome_heroi
  url_hero= f'https://pt.dotabuff.com/heroes/{nome}'
  headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'}
  site_hero = requests.get(url_hero, headers=headers)
  soup_hero = BeautifulSoup(site_hero.text, 'html.parser')

  lista = list()
  for i in soup_hero.find_all('a', attrs={'class': 'link-type-hero'}):
    lista.append(i.text)

  melhor_contra = list()
  pior_contra = list()

  for nome in lista[0:10]:
    melhor_contra.append(nome)

  for nome in lista[10:20]:
    pior_contra.append(nome)

  melhor_contra_string = f'{nome_heroi} melhor contra'
  pior_contra_string = f'{nome_heroi} pior contra'

  dota1 = pd.DataFrame({melhor_contra_string.title(): melhor_contra, pior_contra_string.title(): pior_contra})
  dota1.index = np.arange(1, len(dota1) + 1)
  return dota1

buscar_heroi('abaddon') # O argumento dessa função é o nome de qualquer um dos 124 herois existentes hoje no dota

